"""add automation rules and queued drafts

Revision ID: 9abe206aac55
Revises: 81621bda2b0e
Create Date: 2026-09-26 11:35:48.572198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abe206aac55'
down_revision: Union[str, None] = '81621bda2b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('GMAIL', 'DOCUMENT', name='automation_source'), nullable=False),
    sa.Column('gmail_connector_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('slack_connector_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gmail_connector_id'], ['connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slack_connector_id'], ['connector_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_organization_id'), 'automation_rules', ['organization_id'], unique=False)
    op.create_table('queued_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('source_label', sa.String(length=300), nullable=False),
    sa.Column('slack_connector_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DISMISSED', name='queued_draft_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queued_drafts_organization_id'), 'queued_drafts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queued_drafts_organization_id'), table_name='queued_drafts')
    op.drop_table('queued_drafts')
    op.drop_index(op.f('ix_automation_rules_organization_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
