"""create connector_accounts table

Revision ID: bd1218406a77
Revises: 4356fa52934f
Create Date: 2026-09-25 15:29:33.625393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1218406a77'
down_revision: Union[str, None] = '4356fa52934f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('GOOGLE', name='connector_provider'), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', 'account_email', name='uq_connector_account')
    )
    op.create_index(op.f('ix_connector_accounts_organization_id'), 'connector_accounts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_accounts_organization_id'), table_name='connector_accounts')
    op.drop_table('connector_accounts')
    # ### end Alembic commands ###
